#!/bin/sh

# wonder-romeo - Use uwsgi to run wonder wsgi web app.
#
# chkconfig: - 85 15
# description: Use uwsgi to run wonder wsgi web app.
# processname: uwsgi


. /etc/rc.d/init.d/functions

NAME="`basename $0`"
USER=wonder-romeo
BIN=/usr/sbin/uwsgi
CFG=/etc/wonder/romeo/uwsgi.ini:wonder
LOG=/var/log/$NAME.log
PID=/var/run/$NAME.pid
LOCK=/var/lock/subsys/$NAME
RETVAL=0

export WONDER_SETTINGS=/etc/wonder/romeo/config.py

. /etc/rc.d/init.d/uwsgi-common
