#!/bin/sh

# wonder-romeo - Use uwsgi to run wonder wsgi web app.
#
# chkconfig: - 85 15
# description: Use uwsgi to run wonder wsgi web app.
# processname: uwsgi


. /etc/rc.d/init.d/functions

NAME="`basename $0`"
USER=wonder-romeo
BIN=/usr/sbin/uwsgi
CFG=/etc/wonder/romeo/uwsgi.ini:wonder
LOG=/var/log/$NAME.log
PID=/var/run/$NAME.pid
LOCK=/var/lock/subsys/$NAME
RETVAL=0

WONDER_SETTINGS=/etc/wonder/romeo/config.py

[ -r /etc/sysconfig/$NAME ] && . /etc/sysconfig/$NAME

DAEMON_OPTS="--ini $CFG --daemonize $LOG --pidfile $PID --uid $USER"

export WONDER_SETTINGS


start() {
	# Ensure log file is writable by $USER
	[ -e $LOG ] || install -m 664 -o $USER /dev/null $LOG
	echo -n "Starting $NAME: "
	daemon $BIN $DAEMON_OPTS
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch $LOCK
	return $RETVAL
}

stop() {
	echo -n "Stopping $NAME: "
	killproc -p $PID $NAME
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f $LOCK
	return $RETVAL
}

reload() {
	echo "Reloading $NAME" 
	killproc -p $PID $NAME -HUP
	RETVAL=$?
	echo
}

restart() {
	stop
	sleep 0.1
	start
}

force_reload() {
	restart
}

rh_status() {
	status -p $PID $NAME
}

rh_status_q() {
	rh_status >/dev/null 2>&1
}

case "$1" in
	start)
		rh_status_q && exit 0
		$1
		;;
	stop)
		rh_status_q || exit 0
		$1
		;;
	restart)
		$1
		;;
	reload)
		rh_status_q || exit 7
		$1
		;;
	force-reload)
		force_reload
		;;
	status)
		rh_status
		;;
	condrestart|try-restart)
		rh_status_q || exit 0
		restart
		;;
	*)	
		echo "Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}" >&2
		exit 2
		;;
esac

exit $?
