"""account dolly

Revision ID: 23be4dee8373
Revises: 3f82c6fe9781
Create Date: 2014-03-11 12:25:30.472641

"""

# revision identifiers, used by Alembic.
revision = '23be4dee8373'
down_revision = '3f82c6fe9781'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('dolly_token', sa.String(length=128), nullable=True))
    op.add_column('account', sa.Column('dolly_user', sa.CHAR(length=22), nullable=True))
    op.drop_column('account', 'wonder_user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('wonder_user', sa.CHAR(length=22), nullable=True))
    op.drop_column('account', 'dolly_user')
    op.drop_column('account', 'dolly_token')
    ### end Alembic commands ###
