"""Add video_seo_embed

Revision ID: 274331b97f48
Revises: 3f5c47781ad
Create Date: 2014-06-18 14:56:01.667176

"""

# revision identifiers, used by Alembic.
revision = '274331b97f48'
down_revision = '3f5c47781ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_seo_embed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video', sa.Integer(), nullable=False),
    sa.Column('link_url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['video'], [u'video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_seo_embed')
    ### end Alembic commands ###
