"""video

Revision ID: 3f82c6fe9781
Revises: 506f10ed239e
Create Date: 2014-03-06 23:40:10.035151

"""

# revision identifiers, used by Alembic.
revision = '3f82c6fe9781'
down_revision = '506f10ed239e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('dolly_channel', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['account'], [u'account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('uploading', 'processing', 'error', 'ready', 'published', name='video_status'), nullable=False),
    sa.Column('public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('duration', sa.Integer(), server_default='0', nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['account'], [u'account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_workflow_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_value', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'account_user.id'], ),
    sa.ForeignKeyConstraint(['video'], [u'video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_thumbnail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video'], [u'video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_tag_video',
    sa.Column('video', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag'], [u'video_tag.id'], ),
    sa.ForeignKeyConstraint(['video'], [u'video.id'], ),
    sa.PrimaryKeyConstraint('video', 'tag')
    )
    op.create_table('video_locale_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=False),
    sa.Column('link_url', sa.String(length=2048), nullable=True),
    sa.Column('link_title', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['video'], [u'video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_locale_meta')
    op.drop_table('video_tag_video')
    op.drop_table('video_thumbnail')
    op.drop_table('video_workflow_event')
    op.drop_table('video')
    op.drop_table('video_tag')
    ### end Alembic commands ###
