"""Add description to tag

Revision ID: 542e7a17fca0
Revises: 23be4dee8373
Create Date: 2014-03-28 15:47:52.783978

"""

# revision identifiers, used by Alembic.
revision = '542e7a17fca0'
down_revision = '23be4dee8373'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_tag', sa.Column('description', sa.String(length=200), nullable=False, server_default=''))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_tag', 'description')
    ### end Alembic commands ###
